# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  #config.vm.provision "ansible" do |ansible|
  #  #ansible.verbose = "v"
  #  ansible.playbook = "provisioning/playbook.yml"
  #  ansible.sudo = "true"
  #end

  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "test" do |ns01|
    ns01.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "dns"
    ns01.vm.hostname = "test"
  end

end
