---

- name: vlans
  hosts:
    - testClient1
    - testClient2
    - testServer1
    - testServer2
  become: true
  tags:
    - vlans

  roles:
    - vlans

##########################
- name: bonds
  hosts: bond
  become: true
  tags:
    - bond
  roles:
    - bond
...
