---
- name:  CA SERVER |Generate an OpenSSL private key for CA
  openssl_privatekey:
    path: "{{ pki_private_path }}{{ CA_private_key_name }}"
    size: "{{ CA_private_key_bits }}"

- name:  CA SERVER |Generate an OpenSSL CSR for CA
  openssl_csr:
    path: "{{ pki_certs_path }}{{ CA_private_key_name }}.csr"
    privatekey_path: "{{ pki_private_path }}{{ CA_private_key_name }}"
    email_address: "{{ CA_email_addr }}"
    common_name: "{{ CA_common_name }}"
    country_name: "{{ CA_country_name }}"
    organization_name: "{{ CA_org_name }}"
    basic_constraints_critical: yes
    key_usage:
      - keyCertSign
      - cRLSign
    basicConstraints: ['CA:TRUE']

- name:  CA SERVER |Generate a Self Signed OpenSSL certificate for CA
  openssl_certificate:
    path: "{{ pki_certs_path }}{{ CA_cert_name }}"
    privatekey_path: "{{ pki_private_path }}{{ CA_private_key_name }}"
    csr_path: "{{ pki_certs_path }}{{ CA_private_key_name }}.csr"
    key_usage:
      - keyCertSign
      - cRLSign
    provider: selfsigned
    key_usage_strict: true
...