---
- name: Install epel-release
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - epel-release

- name: Install packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - ntp
    - python2-cryptography
    - setools-console
    - policycoreutils-python
    - python
    - python-pip

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"

- name: Enable ntpd
  systemd:
    name: ntpd
    enabled: true
    state: restarted

- name: "Add my own IP to /etc/hosts instead localhost"
  replace:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1(\s+){{ ansible_hostname }}(\s+){{ ansible_hostname }}.*'
    replace: "{{ ansible_host }} {{ ansible_hostname }}.{{ domain }} {{ ansible_hostname }}"

- name: "Add {{ webserver_hostname }}.{{ domain }} IP to /etc/hosts"
  lineinfile:
    path: /etc/hosts
    line: "{{ webserver_ip }} {{ webserver_hostname }}.{{ domain }} {{ webserver_hostname }}"
    state: present

- name: Temporary Disable SELinux
  selinux:
    state: disabled

# - name: disable firewalld
#   firewalld:
#     state: disabled
...