---
- name: POSTGRESSQL INSTALLL |install postgres repo
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    update_cache: yes
    state: present

- name: POSTGRESSQL INSTALLL |Install packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - postgresql11-server
    - postgresql11-contrib

- name: POSTGRESSQL INSTALLL |Init database
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
  args:
    creates: "{{ postgresql_data_path }}/postgresql.conf"

- name: POSTGRESSQL INSTALLL |enable and start postgres server
  systemd:
    name: postgresql-11.service
    state: started
    enabled: yes
...