---
- name: PHP-FPM | Enable php74 repo
  yum_repository:
    name: remi-php74
    description: Remi's PHP 7.4 RPM repository $releasever - $basearch
    mirrorlist: http://rpms.remirepo.net/enterprise/$releasever/php73/mirror
    enabled: yes
    gpgcheck: 1
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi

- name: PHP-FPM | install packages
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop:
  - "{{ php_pakages }}"
  tags:
    - php-package
    - packages

- name: PHP-FPM | Create workdir for Wordpress
  file:
    path: "{{ php_unix_socket_path }}"
    state: directory
    mode: '0755'

- name: PHP-FPM | Delivery templates for nginx and fastCGI
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    #/etc/nginx/nginx.conf
    mode: 0644
    owner: root
    group: root
  with_items:
    - { src: php-fpm.conf.j2 , dest: "/etc/php-fpm.d/{{ domain }}.conf" }
  notify:
    - restart_php-fpm
  tags:
    - nginx-configuration