# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nginx1 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.110',
  },
}

Vagrant.configure("2") do |config|

      MACHINES.each do |boxname, boxconfig|

      	config.vm.define boxname do |box|

                  box.vm.box = boxconfig[:box_name]
                 	box.vm.host_name = boxname.to_s

                  box.vm.network "private_network", ip: boxconfig[:ip_addr]
                        default_router = "192.168.11.1"

                    case boxname.to_s
                        when "nginx1"
                        box.vm.provider :virtualbox do |vb|
                              vb.customize ["modifyvm", :id, "--memory", "2048"]
                              vb.customize ["modifyvm", :id, "--cpus", "2"]
                              vb.name = boxname.to_s
                        end
                        #box.vm.provision "shell", run: "always", inline: <<-SHELL
                        #      bash +x /vagrant/provision.sh
                        #SHELL
                  end
            end
      end

      config.vm.provision "ansible" do |ansible|
            ansible.playbook = "./ansible/startall.yml"
            ansible.inventory_path = "./ansible/inventory/hosts"
      end
end
