#!/usr/bin/env bash
#Определяем день недели через сервис API. Если недоступен - проверка на выходные встроенными средствами Linux.
DW=$(curl https://isdayoff.ru/`date +%Y%m%d`)
#DW=$(curl https://isdayoff.ru/20190509)
#проверяем - работает ли сервис API
if [[ "$?" -eq 0 ]] 
then
    #Если курл отработал - то  используем значение из cURL
    if [[ "$DW" -eq 1 ]]
      then
        exit 1
      else
        exit 0
      fi
else
    #Если не отработал то авторизация идет через данные системы данные о выходных из файла holidays
    #Смотрим день недели
    HOUR=$(date +%u)
    if [[ "$HOUR" -gt 5 ]]
        then
        exit 1
        elif [[ "grep `date +%d.%m` /vagrant/holidays" ]]
            then
            exit 1
        else
        exit 0
    fi
fi


