# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :elk => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.140',
  },
  :nginx => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.141',
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "4096"]
          vb.name = boxname.to_s

          end

      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL

      case boxname.to_s
      when "elk"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
		  
        yum install epel-release -y
        yum update -y
        yum install ssh mc wget net-tools lsof -y
        # Отключаю SELinux - пока не понимаю почему блокируется
        sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
        #Отключаю сразу, что бы не перезагружаться.
        setenforce 0
        # Разрешаем авторизацию по паролю - если запрещено
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
        
        wget https://s3-eu-west-1.amazonaws.com/portal-custom-assets.smartcat.ai/jre-8u211-linux-x64.rpm
        yum install -y jre-8u211-linux-x64.rpm
        rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
        cp /vagrant/elasticsearch.repo /etc/yum.repos.d/elasticsearch.repo
        yum install -y elasticsearch kibana nginx logstash wget systemd-journal-gateway
        systemctl daemon-reload
        systemctl enable elasticsearch.service
        systemctl start elasticsearch.service
        systemctl enable kibana.service
        systemctl start kibana.service
        cp /vagrant/nginx.conf /etc/nginx/nginx.conf
        systemctl enable nginx.service
        systemctl start nginx.service
        cp /vagrant/input.conf /etc/logstash/conf.d
        cp /vagrant/output.conf  /etc/logstash/conf.d
        cp /vagrant/filter.conf  /etc/logstash/conf.d
        systemctl enable logstash.service
        cd /etc/logstash
        wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
        gunzip GeoLite2-City.mmdb.gz
        sed -i 's/# http.port: 9600-9700/http.port: 9600-9700/' /etc/logstash/logstash.yml
        #sed -i '/[Upload]/a '
        systemctl start logstash.service
        mkdir -p /var/log/journal/remote
        chown systemd-journal-remote:systemd-journal-remote /var/log/journal/remote
        sed -i 's/listen-https/listen-http/' /lib/systemd/system/systemd-journal-remote.service
        systemctl daemon-reload
        systemctl start systemd-journal-remote

        ip -4 a |grep inet --color
      SHELL

    
    when "nginx"
      box.vm.provision "shell", run: "always", inline: <<-SHELL
      
      yum install epel-release -y
      yum update -y
      yum install -y ssh mc nginx systemd-journal-gateway
      curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.4.0-x86_64.rpm
      rpm -vi filebeat-6.4.0-x86_64.rpm
      # Разрешаем авторизацию по паролю - если запрещено
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd
      
      
      # Отключаю SELinux - пока не понимаю почему блокируется
      sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
      #Отключаю сразу, что бы не перезагружаться.
      setenforce 0
      cp /vagrant/nginx/nginx.conf /etc/nginx/nginx.conf
      cp /vagrant/nginx/index.html /usr/share/nginx/html/index.html
      cp /vagrant/filebeat.yml /etc/filebeat/filebeat.yml
      systemctl enable nginx
      systemctl start filebeat
      systemctl enable filebeat
      cp /vargrant/nginx.rules /etc/audit/rules.d
      service auditd restart
      sed -i '/\[Upload\]/a URL=http://192.168.11.140:9600' /etc/systemd/journal-upload.conf
      ip -4 a |grep inet --color
      SHELL
    end







      end
   end
end

