# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :pam => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.140',
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "256"]
          vb.name = boxname.to_s

          end

      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL

      case boxname.to_s
      when "pam"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
		  
		  yum install epel-release -y
      yum install pam_script ssh -y
		  # Разрешаем авторизацию по паролю - если запрещено
		  sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      #0 Добавляем проверку  по условию задачи через скрипт
      mkdir /etc/pamunlockscript
      chmod +x /vagrant/pam_script_auth
      cp /vagrant/pam_script_auth /etc/pamunlockscript/
      
      cp -f /vagrant/sshd /etc/pam.d/
		  systemctl restart sshd
		  groupadd admin
		  useradd -G admin sveta
		  #Устанавливаем супер сложный пароль )))
		  echo qwerty12 | passwd sveta --stdin
		  useradd nastya
		  echo qwerty12 | passwd nastya --stdin
      SHELL
      end

      end
   end
end

