---
# tasks file for grafana
- name: GRAFANA | add grafana repo
  template:
      src: grafana.repo.j2
      dest: /etc/yum.repo/grafana.repo
      mode: '0644'
      owner: root
      group: root

- name: GRAFANA |install grafana rpm from a local file
  yum:
    name: grafana
    state: present

- name: GRAFANA |config grafana server
  lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { path: "/etc/grafana/grafana.ini" , regexp: "^http_port" , line: "http_port = {{ grafana_http_ports }}"  }

  notify:
    - start_grafana
