# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']
# Определяем список машин ддя развертывания
MACHINES = {
  :log => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.140',       
  },
  :nginx => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.141',
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        box.vm.network "private_network", ip: boxconfig[:ip_addr]


        #общий провижн, что применяется для всех тачек
        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
          SHELL

        case boxname.to_s
          when "log"
            # конфигурация для конкретной машины 
            box.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", "4096"]
              vb.customize ["modifyvm", :id, "--cpus", "4"]
              vb.name = boxname.to_s
            end
            # Провижн для конкретной машины 
            box.vm.provision "shell", run: "always", path: "./provision_log.sh"    
          when "nginx"
            # конфигурация для конкретной машины 
            box.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", "512"]
              vb.customize ["modifyvm", :id, "--cpus", "2"]
              vb.name = boxname.to_s
            end
            # Провижн для конкретной машины 
            box.vm.provision "shell", run: "always", path: "./provision_nginx.sh"      
        end

    end
   end
end

