- name: POSTGRES-REPLICATION |Stop postgresql on {{ replica_hostname }}
  systemd:
    name: postgresql-11.service
    state: stopped

- name: POSTGRES-REPLICATION |Clear exist pgdata on {{ replica_hostname }}
  file:
    path: "{{ postgresql_data_path }}"
    state: absent

- name: POSTGRES-REPLICATION |Create empty pgdata on {{ replica_hostname }}
  file:
    path: "{{ postgresql_data_path }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: POSTGRES-REPLICATION |Copy base from {{ master_hostname }} to {{ replica_hostname }}
  command: "pg_basebackup -X stream -h {{ master_hostname }}.{{ domain }} -D {{ postgresql_data_path }}/ -P -U {{ streaming_username }}"
  become: yes
  become_user: postgres
  notify: restart_postgresql_replica

- name: POSTGRES-REPLICATION |Provision {{ postgresql_data_path }}/recovery.conf to replica from template
  template:
    owner: postgres
    group: postgres
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: postgresql-replica.conf.j2, dest: "{{ postgresql_data_path }}/postgresql.conf" }
    - { src: recovery.conf.j2, dest: "{{ postgresql_data_path }}/recovery.conf" }
  notify: restart_postgresql_replica

- name: POSTGRES-REPLICATION |Configuring {{ postgresql_data_path }}/pg_hba.conf on {{ replica_hostname }}
  lineinfile:
    path: "{{ postgresql_data_path }}/pg_hba.conf"
    line: "host replication all {{ master_ip }}/32 trust"
    state: present
  notify: restart_postgresql_replica

- name: POSTGRES-REPLICATION |Create empty archive directory on {{ replica_hostname }}
  file:
    path: "{{ postgresql_path }}/archive"
    state: directory
    owner: postgres
    group: postgres
    mode: '0770'