---
- name: add Ghost group
  group:
    name: "{{ ghost_user_group }}"
    system: yes
    state: present
  become: yes

- name: add Ghost user
  user:
    name: "{{ ghost_user_name }}"
    group: "{{ ghost_user_group }}"
    home: "{{ ghost_user_home }}"
    createhome: yes
    shell: /bin/false
    system: yes
    state: present
  become: yes

- name: fetch Ghost
  get_url:
    url: "{{ ghost_fetch_url }}"
    dest: "{{ ghost_fetch_dir }}/ghost.zip"
  become: yes

- name: change Ghost user home permissions
  file:
    dest: "{{ ghost_user_home }}"
    owner: "{{ ghost_user_name }}"
    group: "{{ ghost_user_group }}"
    mode: 0755
    state: directory
  become: yes

- name: check if Ghost installation path exists
  stat:
    path: "{{ ghost_work_dir }}"
  register: ghost_check_install_dir

- name: create Ghost installation path if necessary
  file:
    dest: "{{ ghost_work_dir }}"
    owner: "{{ ghost_user_name }}"
    group: "{{ ghost_user_group }}"
    mode: 0755
    state: directory
  become: yes
  when: not ghost_check_install_dir.stat.exists

- name: unzip Ghost
  unarchive:
    src: "{{ ghost_fetch_dir }}/ghost.zip"
    dest: "{{ ghost_work_dir }}"
    owner: "{{ ghost_user_name }}"
    group: "{{ ghost_user_group }}"
    copy: no
    creates: "{{ ghost_work_dir }}/index.js"
  become: yes

- name: install Ghost
  npm:
    path: "{{ ghost_work_dir }}"
    production: yes
    state: present
  become: yes
  become_user: "{{ ghost_user_name }}"

- name: add configurations
  template:
    src: config.js.j2
    dest: "{{ ghost_work_dir }}/config.js"
    owner: "{{ ghost_user_name }}"
    group: "{{ ghost_user_group }}"
    mode: 0644
  notify: ghost - restart service
  become: yes

- name: add init script
  template:
    src: init.ghost.j2
    dest: "/etc/init.d/{{ ghost_service_name }}"
    owner: root
    group: root
    mode: 0755
  become: yes
  #become_user: "{{ ghost_user_name }}"

- name: enable Ghost service
  service:
    name: "{{ ghost_service_name }}"
    enabled: yes
    state: started
  become: yes
