# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :mysqlMaster => {
        :box_name => "centos/7",
        :net => [
            {ip: '192.168.11.120', adapter: 2, netmask: "255.255.255.0"},
        ]
      },
  :mysqlSlave => {
      :box_name => "centos/7",
      :net => [
            {ip: '192.168.11.130', adapter: 2, netmask: "255.255.255.0"},
        ]
      },
}

Vagrant.configure("2") do |config|

      MACHINES.each do |boxname, boxconfig|

      	config.vm.define boxname do |box|

                  box.vm.box = boxconfig[:box_name]
                 	box.vm.host_name = boxname.to_s

                  boxconfig[:net].each do |ipconf|
                        box.vm.network "private_network", ipconf
                  end

                  box.vm.provider :virtualbox do |vb|
                        vb.customize ["modifyvm", :id, "--memory", "2048"]
                        vb.customize ["modifyvm", :id, "--cpus", "2"]
                        vb.name = boxname.to_s
                  end

#                    case boxname.to_s
#                        when "mysqlMaster"
#                        box.vm.provider :virtualbox do |vb|
#                              vb.customize ["modifyvm", :id, "--memory", "2048"]
#                              vb.customize ["modifyvm", :id, "--cpus", "2"]
#                              vb.name = boxname.to_s
#                        end
#                        when "mysqlSlave"
#                              box.vm.provider :virtualbox do |vb|
#                                    vb.customize ["modifyvm", :id, "--memory", "2048"]
#                                    vb.customize ["modifyvm", :id, "--cpus", "2"]
#                                    vb.name = boxname.to_s
#                        end
                        box.vm.provision "shell", run: "always", inline: <<-SHELL
                              bash +x /vagrant/provision.sh
                        SHELL
                  #end
            end
      end

      config.vm.provision "ansible" do |ansible|
            ansible.playbook = "./ansible/startall.yml"
            ansible.config_file = "./ansible/ansible.cfg"
            ansible.inventory_path = "./ansible/inventory/hosts"
            ansible.verbose = "vv"
      end

end
