---

  become_user: True
- task:
  - name: TEst



     - yum:
        name: "{{ packages }}"
           state: latest
        vars:
           packages:
           - nginx
           - mc
           -
