---
# handlers file for mysql
- name: restart_mysql
  systemd:
    name: mysql
    state: restarted
    enabled: yes

- name: start_mysql
  systemd:
    name: mysql
    state: started
    enabled: yes
...