---
 - name: AUDITD_CLIENT | Install&run auditd
   block:

    - name: AUDITD_CLIENT | Install auditd
      yum:
        name: audit
        state: present
      tags:
        - packages

    - name: AUDITD_CLIENT |audispd-plugins install # Ставим нужные пакеты
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - audispd-plugins


    - name: AUDITD_CLIENT |configuring /etc/audisp/au-remote.conf #Включаем передачу данных на удаленный сервер
      replace:
        path: /etc/audisp/plugins.d/au-remote.conf
        regexp: 'active = no'
        replace: "active = yes"


    - name: AUDITD_CLIENT |configuring /etc/audisp/audisp-remote.conf # Указываем сервер, куда слать данные
      replace:
        path: /etc/audisp/audisp-remote.conf
        regexp: '^remote_server = *$'
        replace: "remote_server = {{ log_server }}"


    - name: AUDITD_CLIENT |create /etc/audit/rules.d/nginx.rules # Создадим файл правил для nginx
      file:
        path: /etc/audit/rules.d/nginx.rules
        state: touch


    - name: AUDITD_CLIENT |insert rule to /etc/audit/rules.d/nginx.rules # Будем отслеживать изменения в каталоге /etc/nginx/
      lineinfile:
        path: /etc/audit/rules.d/nginx.rules
        line: "{{ audit_target }}"
        state: present
      notify: restart_auditd
