galaxy_info:
  author: Agafonov Andrey
  description: Deploy postgreecluster patroni
  company: clou16.ru
  min_ansible_version: 2.9
  galaxy_tags:
    - postgresql
    - postgresql-cluster
dependencies:
  - prepare
