INTENT_TYPE="internal-net"

MACHINES = {
  :consul => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.10', adapter: 3, netmask: "255.255.255.0"},
                     ],
            },
  :node1 => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.21', adapter: 3, netmask: "255.255.255.0"},
                     ],
            },
  :node2 => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.22', adapter: 3, netmask: "255.255.255.0"},
                     ],
            },
  :node3 => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.23', adapter: 3, netmask: "255.255.255.0"},
                     ],
            },
  :ansible => {
    :box_name => "centos/7",
    :net => [
              {ip: '192.168.56.20', adapter: 3, netmask: "255.255.255.0"},
            ],
    },
}


# hosts_file="127.0.0.1\tlocalhost\n"

#MACHINES.each do |hostname,config|
#   config[:net].each do |ip|
#     # if ip[:virtualbox__intnet]==INTENT_TYPE
#     #   hosts_file=hosts_file+ip[:ip]+"\t"+hostname.to_s+"\n"
#     # end
#   end
# end

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        box.vm.provider "virtualbox" do |v|
          v.memory = 1024
        end
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          bash +x /vagrant/provision.sh
          # shell.inline = 'echo -e "$1" > /etc/hosts'
          # shell.args = [hosts_file]
          SHELL

        # box.vm.provision "ansible" do |ansible|
        #   ansible.compatibility_mode = "2.0"
        #   ansible.verbose = "true"
        #   ansible.playbook = "ansible/postgres-cluster.yml"
        #   #ansible.tags = "all"
        # end
        case boxname.to_s
        when "ansible"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            bash +x /vagrant/ansible/provision.sh
          SHELL
        end
    end
  end
end

