---
# tasks file for provision/roles/patroni

# - name: PATRONI | install epel
#   yum:
#     name: epel-release
#     state: present

- name: PATRONI | Install patroni requiered packages
  yum:
    name: "{{ packages }}"
    state: present

- name: PATRONI | install postgresql-11 repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: PATRONI | Install postgresql-11-server
  yum:
    name: "{{ packages_psql }}"
    state: present
  vars:
    packages_psql:
    - postgresql11-server
    - postgresql11-contrib

- name: PATRONI | Upgrade pip
  pip:
    name: pip
    state: forcereinstall

- name: PATRONI | Install pip packages
  pip:
    name: "{{ pip_packages }}"
    state: present


- name: PATRONI | Upgrade setuptools
  pip:
    name: setuptools
    state: forcereinstall

- name: PATRONI | Install patroni
  pip:
    name: patroni
    state: present


- name: PATRONI | Configure patroni systemd service file
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service

- name: PATRONI | Create patroni directories
  file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  with_items:
      - /var/data/base
      - /etc/patroni/
  tags:
    - dirs

- name: PATRONI | Copy patroni config file
  template:
    src: patroni.yml.j2
    dest: /etc/patroni/patroni.yml

- name: PATRONI | Start patroni cluster
  systemd:
    name: patroni
    state: restarted
    daemon_reload: True
    enabled: true

- name: PATRONI | place bashrc file
  template:
    src: bashrc.j2
    dest: /root/.bashrc

