---
# defaults file for ghost

ghost_mysql_db: ghost
ghost_mysql_user: ghost_mysql
ghost_mysql_password: "80mGl[wTEt"
ghost_mysql_host: "%"
ghost_work_dir: /opt/ghost

ghost_fetch_url: https://ghost.org/zip/ghost-latest.zip
ghost_fetch_dir: /tmp

ghost_nodejs_pin_priority: 500
ghost_nodejs_path: /usr/bin/node

ghost_service_name: "{{ ghost_work_dir | basename }}"
ghost_internal_url: http://{{ ghost_config_server.host }}:{{ ghost_config_server.port }}

ghost_user_name: ghost_user
ghost_user_group: ghost_user
ghost_user_home: "{{ ghost_work_dir | dirname }}"

ghost_config_url: http://{{ ghost_config_server.host }}:{{ ghost_config_server.port }}
ghost_config_mail: {}
ghost_config_database:
  client: "mysql"
  connection:
    filename: "{{ ghost_work_dir }}/content/data/ghost.db"
  debug: "false"
ghost_config_server:
  host: "127.0.0.1"
  port: "2368"

ghost_nodejs_enabled: yes

ghost_nginx_enabled: yes
ghost_nginx_port: 80
ghost_nginx_admin_allowed_cidr: "127.0.0.1/32"

ghost_nginx_sites:
  default:
    - listen {{ ghost_nginx_port }}
    - server_name {{ ghost_config_server.host }}
    - proxy_set_header X-Real-IP $remote_addr
    - proxy_set_header Host $http_host
    - location / { proxy_pass {{ ghost_internal_url }}; }
    - location ~ ^/ghost/setup { allow {{ ghost_nginx_admin_allowed_cidr }}; deny all; }