# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.network "private_network", ip: "192.168.11.10", virtualbox__intnet: "local"
    mysql.vm.hostname = "mysql"
  end

  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vvv"
    ansible.playbook = "mysqlcluster.yml"
    ansible.become = "true"
  end

end
